// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXHLRS65_qSjdRelkAQogjcMxt06uXTLw',
    appId: '1:884502786471:web:8276d4e8ac6b68ae9a4682',
    messagingSenderId: '884502786471',
    projectId: 'roadway-core',
    authDomain: 'roadway-core.firebaseapp.com',
    databaseURL: 'https://roadway-core-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadway-core.appspot.com',
    measurementId: 'G-XZG6F0HG1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIse5zEqNUNZmlOEATdxSW-XeyOQQULQ8',
    appId: '1:884502786471:android:e3b64adeedf84fed9a4682',
    messagingSenderId: '884502786471',
    projectId: 'roadway-core',
    databaseURL: 'https://roadway-core-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadway-core.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1-Uo9DPUdKP3atZ8oM6GcyKoJW6sZen8',
    appId: '1:884502786471:ios:e0df1ab3719ca7dd9a4682',
    messagingSenderId: '884502786471',
    projectId: 'roadway-core',
    databaseURL: 'https://roadway-core-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadway-core.appspot.com',
    androidClientId: '884502786471-faohqbb2c6grc0rb8cth289u7q9qvbud.apps.googleusercontent.com',
    iosClientId: '884502786471-9ubkfsr78d0qhqo08kndsja8rspk64n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpressnepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1-Uo9DPUdKP3atZ8oM6GcyKoJW6sZen8',
    appId: '1:884502786471:ios:e0df1ab3719ca7dd9a4682',
    messagingSenderId: '884502786471',
    projectId: 'roadway-core',
    databaseURL: 'https://roadway-core-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadway-core.appspot.com',
    androidClientId: '884502786471-faohqbb2c6grc0rb8cth289u7q9qvbud.apps.googleusercontent.com',
    iosClientId: '884502786471-9ubkfsr78d0qhqo08kndsja8rspk64n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpressnepal',
  );
}
